### ISSUE TITLE
Create a home page

### ISSUE THREAD

**Issue by petrusmatiros** [petrusmatiros/didyousee#1]
### Is your feature request related to a problem?
nope

### Describe the solution you'd like
To create a functional and visually pleasant home page. The home page should enable routing between different views (such as the profile page), allow for search of movies/series, apply filters to the search, view recommended movies/series. The home page should also include trivia/fun facts below the home page title.

### Describe alternatives you've considered
An alternative would be a more basic home page, with only the search feature (together with filters).

### Additional context/notes
none

**Comment by Blezie** [comment]
Ska vi stänga den här?

**Comment by petrusmatiros** [comment]
Done
