### ISSUE TITLE
Back Button on Result Page/View

### ISSUE THREAD

**Issue by Blezie** [petrusmatiros/didyousee#19]
### Is your feature request related to a problem?
The user's previous input may be lost when they navigate away from the result page/view.

### Describe the solution you'd like
Implement a back button on the result page/view that allows users to easily navigate back to the input page/view, ensuring that their previous input is saved. This can be a simple button or link that takes users back to the previous page (Home).

**Comment by Blezie** [comment]
Created a simple back button in the Result View. However, it needs CSS styling.

**Comment by petrusmatiros** [comment]
We should do this instead for the result page #25 
Other views can use the back button

**Comment by Blezie** [comment]
Stänga?

**Comment by petrusmatiros** [comment]
Done
