### ISSUE TITLE
Create a login page

### ISSUE THREAD

**Issue by petrusmatiros** [petrusmatiros/didyousee#3]
### Is your feature request related to a problem?
nope

### Describe the solution you'd like
A login page to allow users to have personal accounts, with their personal content (movie/series lists)

### Describe alternatives you've considered
An alternative would be to use Google, Apple or any other OAuth provider to make it easier to login

### Additional context/notes
none

**Comment by Blezie** [comment]
Ska vi stänga den här?

**Comment by petrusmatiros** [comment]
Done
