### ISSUE TITLE
Create a result page (movie / series)

### ISSUE THREAD

**Issue by petrusmatiros** [petrusmatiros/didyousee#7]
### Is your feature request related to a problem?
nope

### Describe the solution you'd like
Add a result page, which showcases either a movie or a series. The page should contain a poster, title, description/overview, genre, official language and other relevant information. The page should have a clear and visually pleasing layout, which makes it easy to understand the information and navigate through it. There should be easy to reach buttons, that allow users to add said content into one of their personal lists (liked, watchlist, seen, disliked). The buttons should showcase their state clearly.

### Describe alternatives you've considered
none

### Additional context/notes
none

**Comment by Blezie** [comment]
Stänga?

**Comment by petrusmatiros** [comment]
Inte än, vi har en bit att fixa här

**Comment by petrusmatiros** [comment]
Vi behöver fixa designen + lägga till relevant formaterings funktioner backend

**Comment by petrusmatiros** [comment]
Done
